export const BASE_RECTANGLE_WIDTH = 120;
export const BASE_RECTANGLE_HEIGHT = 60;
export const BASE_RECTANGLE_COLOR = "#f0f0f0";
export const BASE_RECTANGLE_BORDER_WIDTH = 1;
export const MIN_RECTANGLE_WIDTH = 60;
export const MIN_RECTANGLE_HEIGHT = 30;
export const DEFAULT_WIDTH_INCREMENT = 4;
export const DEFAULT_HEIGHT_INCREMENT = 2;
export const NODE_DEFAULT_NAME = "New Node";
